name: TajCICD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  lint-check:
    name: Lint
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Lint check
          run: ./gradlew lint
        - name: Generate lint report
          uses: actions/upload-artifact@v2
          with:
            name: lint_report.html
            path: app/build/reports/lint-results-debug.html

  generate-apk:
    name: ️Generate APK
    needs:
      - build
      - lint-check
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build debug apk
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload debug apk
        uses: actions/upload-artifact@v1
        with:
          name: TajCICD
          path: app/build/outputs/apk/debug/app-debug.apk
